parameters:
#    gestion_publication.example.class: FLSHR\gestionPublicationBundle\Example

services:
#    gestion_publication.example:
#        class: %gestion_publication.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
